import {Plus,Trash2,Boxes,Clock,Ban} from 'lucide-react'
import {ContentHeading} from './PageContentUI'
import type {InterestForm as FormValue,InterestEntry} from '../types'
export const emptyForm:FormValue={description:'',long_term:[],temporary:[],exclusions:[]}
export function InterestForm({value,onChange}:{value:FormValue;onChange:(v:FormValue)=>void}){
 const entries=(key:'long_term'|'temporary',title:string)=><div className="interest-section"><ContentHeading icon={key==='long_term'?Boxes:Clock} title={title} level="h3" action={<button type="button" onClick={()=>onChange({...value,[key]:[...value[key],{text:'',weight:.7,until:null}]})}><Plus size={14}/>添加兴趣</button>}/><p className="hint">{key==='long_term'?'持续关注的研究方向，用于论文推荐和方向趋势。':'当前阶段重点关注的方向，可设置结束日期；未设置时持续生效。'}</p>{value[key].map((entry,index)=>{
  const update=(patch:Partial<InterestEntry>)=>onChange({...value,[key]:value[key].map((item,i)=>i===index?{...item,...patch}:item)})
  return <div className="interest-entry" key={index}><label><span className="interest-field-caption">兴趣内容</span><input aria-label={`${title} ${index+1}`} value={entry.text} maxLength={500} onChange={e=>update({text:e.target.value})} placeholder="例如：智能体长期记忆"/></label><label><span className="interest-field-caption">关注程度</span><select aria-label={`${title}关注程度 ${index+1}`} value={entry.weight} onChange={e=>update({weight:Number(e.target.value)})}>{![.4,.7,1].includes(entry.weight)&&<option value={entry.weight}>当前程度</option>}<option value={.4}>一般关注</option><option value={.7}>持续关注</option><option value={1}>重点关注</option></select></label>{key==='temporary'&&<label><span className="interest-field-caption">结束日期</span><input type="date" aria-label={`近期关注结束日期 ${index+1}`} value={entry.until||''} onChange={e=>update({until:e.target.value||null})}/></label>}<button type="button" className="icon-button" aria-label={`删除${title} ${index+1}`} onClick={()=>onChange({...value,[key]:value[key].filter((_,i)=>i!==index)})}><Trash2 size={16}/></button></div>
 })}{!value[key].length&&<p className="hint">点击“添加兴趣”填写您关注的方向。</p>}</div>
 return <div className="interest-form"><label>研究方向描述<textarea aria-label="研究方向描述" rows={3} maxLength={2000} value={value.description} onChange={e=>onChange({...value,description:e.target.value})} placeholder="介绍研究背景、正在解决的问题和已有经验。"/><span className="hint">供智能助手理解背景。用于推荐和趋势的方向，请在下方填写兴趣或选择主题。</span></label>{entries('long_term','长期兴趣')}{entries('temporary','近期关注')}<label><span className="interest-label"><Ban size={20} aria-hidden="true"/>不感兴趣的方向</span><textarea aria-label="不感兴趣的方向" rows={3} value={value.exclusions.join('\n')} onChange={e=>onChange({...value,exclusions:e.target.value.split('\n')})} placeholder="每行一个方向，可随时删除或修改。"/></label>{!!value.inferred?.length&&<div className="inferred-interests"><h3>系统观察到的兴趣</h3><p className="hint">根据阅读反馈更新。</p><ul>{value.inferred.map((item,i)=><li key={i}>{item}</li>)}</ul></div>}</div>
}
