import {useEffect,useState,lazy,Suspense} from 'react'
import '../model-settings.css'
const SkillsSettings=lazy(()=>import('./SkillsSettings').then(m=>({default:m.SkillsSettings})))
import {Plus,RefreshCw,Check,Search,LayoutGrid,List,SlidersHorizontal,Cloud,Monitor,FileText,BookOpen,Brain,Database,Tags,ShieldCheck,Languages,TrendingUp,ClipboardCheck,MessageSquare,ScanText,BookMarked,UserRound,History,Info,Eye,EyeOff,Box} from 'lucide-react'
import {api} from '../api'
import {randomId} from '../randomId'
import {copyText} from '../clipboard'
import {useLoad} from '../hooks/useLoad'
import {useApp} from '../context'
import {Loading,ErrorBox} from './Common'
import {PromptSettings} from './PromptSettings'
import {SettingsDialog,SettingsBlock,ConnectionCard,ConnectionIcon,FeatureGroup,FeatureCard,CodexTaskNotice,kindNames} from './ModelSettingsUI'

type Thinking='auto'|'on'|'off'
type Caps={thinking_modes:Thinking[];reasoning_efforts:string[];note:string;capability_source?:string;type?:string;embedding_dimensions?:number[]}
type Model=Caps&{id:string;name:string}
type Compatibility={active_version?:string;latest_version?:string;checked_at?:string;validated_at?:string;validation_model?:string;warning?:string|null;error?:string|null}
type Catalog={models:Model[];updated_at:string|null;error?:string|null;compatibility?:Compatibility}
type Auth={logged_in:boolean;status:string;user_code?:string;verification_url?:string}
type Connection={id:string;name:string;kind:'ollama'|'cloud'|'codex';base_url:string;configured:boolean;api_key?:string;clear_key?:boolean;credential_revision?:string;oauth_client_id?:string;codex_auto_update?:boolean;codex_client_version?:string;catalog?:Catalog;auth?:Auth;embedding_retained?:boolean}
type Selection={connection_id:string;model:string;thinking?:Thinking;reasoning_effort?:string}
type Route={primary:Selection;fallback:Selection|null}
type Config={connections:Connection[];routes:Record<string,Route>;embedding_dim:number;has_vectors?:boolean;brief_cloud_concurrency:number;quality_cloud_concurrency:number;classify_cloud_concurrency:number;reading_cloud_concurrency:number;reading_local_concurrency:number;embedding_cloud_concurrency:number;embedding_local_concurrency:number;features:{id:string;name:string;requirement:string}[];pending_rebuild?:{status:string;error:string;completed:number;total:number;index_completed?:number;index_total?:number;config:Config}|null}
const featureName=(feature:Config['features'][number])=>feature.id==='chat'?'智能助手':feature.name
const thinkingNames={auto:'跟随模型默认',on:'开启思考',off:'关闭思考'}
const effortNames:Record<string,string>={auto:'模型默认',none:'无',minimal:'最低',low:'低',medium:'中',high:'高',xhigh:'更高',max:'最高',ultra:'极高'}
const sourceNames:Record<string,string>={api:'服务返回',official:'已核对的官方规格',manual:'管理员补充',unknown:'尚未确认'}
const CODEX_URL='https://chatgpt.com/backend-api/codex'
const canonicalModel=(connection:Connection|undefined,model:string)=>connection?.kind==='ollama'&&!model.split('/').at(-1)?.includes(':')?model+':latest':model

function ModelChoice({label,feature,binding,connections,onChange,mode='all'}:{label:string;feature:string;binding:Selection;connections:Connection[];onChange:(value:Selection)=>void;mode?:'all'|'model'|'advanced'}){
 const [caps,setCaps]=useState<Caps|null>(null),[loading,setLoading]=useState(false),[search,setSearch]=useState(''),[manual,setManual]=useState(false)
 const connection=connections.find(c=>c.id===binding.connection_id),cached=connection?.catalog?.models.find(m=>canonicalModel(connection,m.id)===canonicalModel(connection,binding.model))
 useEffect(()=>{
  if(cached){setCaps(cached);setLoading(false);return}
  if(feature==='embedding'||!connection||!binding.model.trim()){setCaps(null);setLoading(false);return}
  const controller=new AbortController();setLoading(true);setCaps(null)
  const timer=setTimeout(()=>{api<Caps>('/admin/models/capabilities','POST',{connection,model:binding.model},controller.signal).then(setCaps).catch(()=>{if(!controller.signal.aborted)setCaps({thinking_modes:['auto'],reasoning_efforts:[],note:'无法确认能力，请更新可用模型。'})}).finally(()=>{if(!controller.signal.aborted)setLoading(false)})},250)
  return()=>{clearTimeout(timer);controller.abort()}
 },[connection?.id,connection?.kind,connection?.base_url,connection?.credential_revision,binding.model,feature,cached])
 const choices=(connection?.catalog?.models||[]).filter(m=>(feature==='embedding'?m.type==='embedding':m.type!=='embedding')&&(m.id+' '+m.name).toLowerCase().includes(search.toLowerCase()))
 const missing=!!connection?.catalog?.updated_at&&!!binding.model&&!connection.catalog.models.some(m=>canonicalModel(connection,m.id)===canonicalModel(connection,binding.model))
 const pickerModel=cached?.id||binding.model
 const modeValue=binding.thinking||'auto',effort=binding.reasoning_effort||'auto'
 return <div className="model-choice-group">
  {mode!=='advanced'&&<><div className="mc-picker-fields"><label>模型连接<select aria-label={label+'连接'} value={binding.connection_id} onChange={e=>{setSearch('');onChange({connection_id:e.target.value,model:'',thinking:'auto',reasoning_effort:'auto'})}}><option value="">请选择连接</option>{connections.filter(c=>(!c.embedding_retained||c.id===binding.connection_id)&&(feature!=='embedding'||c.kind!=='codex')).map(c=><option value={c.id} key={c.id} disabled={c.embedding_retained}>{c.embedding_retained?'当前向量配置':kindNames[c.kind]} · {c.name}</option>)}</select></label><label>搜索可用模型<div className="mc-input-icon"><Search size={17}/><input aria-label={label+'搜索模型'} value={search} placeholder="输入模型名称筛选" onChange={e=>setSearch(e.target.value)}/></div></label></div>
  <label>可用模型<select aria-label={label+'模型'} value={pickerModel} onChange={e=>onChange({...binding,model:e.target.value,thinking:'auto',reasoning_effort:'auto'})}><option value="">请选择模型</option>{binding.model&&!choices.some(m=>m.id===pickerModel)&&<option value={pickerModel} disabled={missing}>{binding.model}{missing?'（不在最新目录）':''}</option>}{choices.map(m=><option key={m.id} value={m.id}>{m.name||m.id}</option>)}</select></label>
  <small className="mc-field-hint">{connection?.catalog?.updated_at?`目录包含 ${connection.catalog.models.length} 个模型，当前匹配 ${choices.length} 个`:'请在模型连接中更新可用模型，也可以直接输入模型名称。'}</small>
  <label className="mc-check-row"><input type="checkbox" checked={manual} onChange={e=>setManual(e.target.checked)}/><span>手动输入模型名称<small>适用于服务支持的模型别名或未列入目录的模型。</small></span></label>{manual&&<label>模型名称<input aria-label={label+'手填模型'} value={binding.model} placeholder="输入服务使用的模型 ID" onChange={e=>onChange({...binding,model:e.target.value,thinking:'auto',reasoning_effort:'auto'})}/></label>}
  {missing&&<p className="mc-inline-notice warning">当前配置的模型已不在最新目录，请重新选择；服务支持的别名可手动确认。</p>}</>}
  <CodexTaskNotice feature={feature} visible={connection?.kind==='codex'}/>
  {mode!=='model'&&feature!=='embedding'&&<><div className="model-controls"><label>思考模式<select disabled={loading||!caps} value={modeValue} onChange={e=>onChange({...binding,thinking:e.target.value as Thinking,reasoning_effort:'auto'})}>{Array.from(new Set<Thinking>(['auto',...(caps?.thinking_modes||[]),modeValue])).map(value=><option key={value} value={value} disabled={value!=='auto'&&!caps?.thinking_modes.includes(value)}>{thinkingNames[value]}</option>)}</select></label><label>推理强度<select disabled={loading||!caps?.reasoning_efforts.length||modeValue==='off'} value={effort} onChange={e=>onChange({...binding,reasoning_effort:e.target.value})}><option value="auto">模型默认</option>{Array.from(new Set([...(caps?.reasoning_efforts||[]),...(effort==='auto'?[]:[effort])])).map(value=><option value={value} key={value} disabled={!caps?.reasoning_efforts.includes(value)||modeValue==='on'&&value==='none'}>{effortNames[value]||value}</option>)}</select></label></div><p className="model-control-note">{loading?'正在读取模型能力…':caps?`${sourceNames[caps.capability_source||'unknown']} · ${caps.note||'未提供的控制项不会开放。'}`:'选择模型后显示可用控制项。'}</p></>}
 </div>
}

function CapabilityEditor({connection,onCatalog,onClose}:{connection:Connection;onCatalog:(value:Catalog)=>void;onClose:()=>void}){
 const [model,setModel]=useState(''),[on,setOn]=useState(false),[off,setOff]=useState(false),[efforts,setEfforts]=useState(''),[type,setType]=useState('unknown'),[protocol,setProtocol]=useState('openai'),[busy,setBusy]=useState(false),[error,setError]=useState('')
 useEffect(()=>{const m=connection.catalog?.models.find(m=>m.id===model);if(m){setOn(m.thinking_modes.includes('on'));setOff(m.thinking_modes.includes('off'));setEfforts(m.reasoning_efforts.join(','));setType(m.type||'unknown');setProtocol(connection.kind==='codex'?'responses':connection.kind==='ollama'?'ollama':(m as Model&{protocol?:string}).protocol||'openai')}},[model,connection.catalog,connection.kind])
 const save=async(reset:boolean)=>{setBusy(true);setError('');try{onCatalog(await api<Catalog>('/admin/models/capability-override','POST',{connection,model,reset,thinking_modes:['auto',...(on?['on']:[]),...(off?['off']:[])],reasoning_efforts:efforts.split(',').map(s=>s.trim()).filter(Boolean),protocol,type}))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const selected=connection.catalog?.models.find(m=>m.id===model)
 const selectedEfforts=efforts.split(',').map(s=>s.trim()).filter(Boolean)
 const effortOptions=Array.from(new Set(['low','medium','high','xhigh',...selectedEfforts]))
 return <SettingsDialog title="补充模型能力" description={connection.name+' · '+kindNames[connection.kind]} icon={<span className="mc-dialog-feature-icon"><SlidersHorizontal size={25}/></span>} error={error} onClose={onClose} footer={<div className="mc-capability-footer"><button type="button" disabled={!model||busy} onClick={()=>void save(true)}><RefreshCw size={15}/>恢复服务规格</button><div className="mc-capability-footer-actions"><button type="button" onClick={onClose}>取消</button><button type="button" className="primary" disabled={!model||busy} onClick={()=>void save(false)}><Check size={16}/>{busy?'处理中…':'保存能力'}</button><small>保存后立即生效</small></div></div>}>
  <div className="mc-capability-editor">
   <section className="mc-capability-section">
    <h3><Box size={19}/>选择模型</h3>
    <select aria-label="补充能力的模型" value={model} onChange={e=>setModel(e.target.value)}><option value="">请选择模型</option>{connection.catalog?.models.map(m=><option key={m.id} value={m.id}>{m.id}</option>)}</select>
    {selected?<div className="mc-capability-model-summary"><strong>{selected.id}</strong><span>{sourceNames[selected.capability_source||'unknown']}</span></div>:<p className="mc-capability-empty">选择模型后，查看和补充它支持的能力。</p>}
    <p className="mc-capability-hint">仅在核对服务文档后填写；管理员补充的能力在目录更新后仍保留。</p>
   </section>
   {model&&<>
    <section className="mc-capability-section">
     <h3><FileText size={19}/>基础能力</h3>
     <div className="mc-capability-columns"><label>模型类型<select aria-label="模型类型" value={type} onChange={e=>setType(e.target.value)}><option value="unknown">尚未确认</option><option value="chat">文本生成</option><option value="embedding">向量模型</option></select></label><label>控制协议<select aria-label="控制协议" value={protocol} onChange={e=>setProtocol(e.target.value)} disabled={connection.kind!=='cloud'}><option value="openai">OpenAI 兼容（reasoning_effort）</option><option value="bailian">百炼（enable_thinking）</option><option value="deepseek">DeepSeek（thinking.type）</option><option value="ollama">Ollama</option><option value="responses">Responses</option></select></label></div>
    </section>
    <section className="mc-capability-section">
     <h3><Brain size={19}/>思考能力</h3>
     <div className="mc-capability-columns mc-capability-toggles">
      <label className="mc-capability-toggle"><span><strong>支持开启思考</strong><small>允许功能分配选择开启思考</small></span><input type="checkbox" role="switch" aria-label="支持开启思考" checked={on} onChange={e=>setOn(e.target.checked)}/><span aria-hidden="true" className="mc-capability-switch"/></label>
      <label className="mc-capability-toggle"><span><strong>支持关闭思考</strong><small>允许功能分配选择关闭思考</small></span><input type="checkbox" role="switch" aria-label="支持关闭思考" checked={off} onChange={e=>setOff(e.target.checked)}/><span aria-hidden="true" className="mc-capability-switch"/></label>
     </div>
     <p className="mc-capability-hint mc-capability-info"><Info size={15}/>这里只声明模型能力，实际使用方式在功能分配中设置。</p>
    </section>
    <section className="mc-capability-section">
     <h3><SlidersHorizontal size={19}/>推理档位</h3>
     <p className="mc-capability-hint">选择服务支持的档位，也可直接填写英文接口值。</p>
     <div className="mc-capability-efforts">{effortOptions.map(effort=><label key={effort}><input type="checkbox" checked={selectedEfforts.includes(effort)} onChange={e=>setEfforts((e.target.checked?[...selectedEfforts,effort]:selectedEfforts.filter(value=>value!==effort)).join(','))}/><span>{effortNames[effort]&&<>{effortNames[effort]} · </>}{effort}</span></label>)}</div>
     <label className="mc-capability-custom">英文接口值（逗号分隔）<input value={efforts} onChange={e=>setEfforts(e.target.value)} placeholder="如 low,medium,high"/></label>
     <p className="mc-capability-hint">只保存选中的档位，也可填写服务支持的自定义档位。</p>
    </section>
   </>}
  </div>
 </SettingsDialog>
}

export function ModelSettings(){
 const result=useLoad<Config>('/admin/models'),{toast}=useApp(),[draft,setDraft]=useState<Config|null>(null),[busy,setBusy]=useState(false),[working,setWorking]=useState<string|null>(null),[statuses,setStatuses]=useState<Record<string,{ok:boolean;message:string}>>({}),[error,setError]=useState(''),[rebuild,setRebuild]=useState(false),[tab,setTab]=useState<'connections'|'routing'|'prompts'|'skills'>('connections'),[visitedInstructions,setVisitedInstructions]=useState<string[]>([])
 useEffect(()=>{if(result.data){setDraft(result.data);setRebuild(false)}},[result.data])
 useEffect(()=>{if(!result.data?.pending_rebuild)return;const timer=setInterval(result.reload,5000);return()=>clearInterval(timer)},[!!result.data?.pending_rebuild,result.reload])

 const [filter,setFilter]=useState<'all'|Connection['kind']>('all'),[search,setSearch]=useState(''),[sort,setSort]=useState('updated'),[view,setView]=useState<'grid'|'list'>('grid')
 const [connectionEditor,setConnectionEditor]=useState<{value:Connection;isNew:boolean;advanced:boolean}|null>(null),[showKey,setShowKey]=useState(false),[catalogId,setCatalogId]=useState<string|null>(null),[catalogSearch,setCatalogSearch]=useState(''),[capabilityId,setCapabilityId]=useState<string|null>(null)
 const [connectionRebuild,setConnectionRebuild]=useState(false)
 const [readingEditor,setReadingEditor]=useState<{cloud:number;local:number}|null>(null)
 const [featureEditor,setFeatureEditor]=useState<{id:string;mode:'model'|'advanced';route:Route;brief_cloud_concurrency:number;quality_cloud_concurrency:number;classify_cloud_concurrency:number;embedding_cloud_concurrency:number;embedding_local_concurrency:number;embedding_dim:number;rebuild:boolean}|null>(null)
 const waiting=draft?.connections.filter(c=>c.auth?.status==='waiting').map(c=>c.id).join(',')||''
 useEffect(()=>{
  if(!waiting)return
  const controller=new AbortController();let polling=false
  const timer=setInterval(async()=>{if(polling)return;polling=true;try{for(const id of waiting.split(',')){const auth=await api<Auth>('/admin/models/codex/'+id+'/poll','POST',{},controller.signal);if(controller.signal.aborted)return;setDraft(d=>d&&({...d,connections:d.connections.map(c=>c.id===id?{...c,configured:auth.logged_in,auth:auth.status==='waiting'?{...c.auth,...auth}:auth}:c)}));if(auth.status==='ready')toast('Codex 登录成功，可以更新模型目录并保存配置')}}catch(e){if(!controller.signal.aborted)setError((e as Error).message)}finally{polling=false}},5000)
  return()=>{clearInterval(timer);controller.abort()}
 },[waiting,toast])
 if(result.error)return <ErrorBox error={result.error} reload={result.reload}/>
 if(!draft)return <Loading/>
 const signature=(config:Config)=>{const binding=config.routes.embedding.primary,connection=config.connections.find(c=>c.id===binding.connection_id);return JSON.stringify([connection?.kind,connection?.base_url.replace(/\/$/,''),canonicalModel(connection,binding.model),config.embedding_dim])}
 const requiresVectorRebuild=(config:Config)=>signature(config)!==signature(result.data||draft)&&!!((result.data||draft).routes.embedding.primary.model||(result.data||draft).has_vectors)
 const embeddingChanged=!!result.data&&requiresVectorRebuild(draft)
 const action=async(connection:Connection,refresh:boolean)=>{setWorking(connection.id);try{const response=await api<Catalog&{ok:boolean;message:string}>('/admin/models/'+(refresh?'refresh':'connection-test'),'POST',connection);setStatuses(s=>({...s,[connection.id]:response}));if(refresh)setDraft(d=>d&&({...d,connections:d.connections.map(c=>c.id===connection.id?{...c,catalog:response}:c)}))}catch(e){setStatuses(s=>({...s,[connection.id]:{ok:false,message:(e as Error).message}}))}finally{setWorking(null)}}
 const login=async(connection:Connection)=>{setWorking(connection.id);setError('');try{const auth=await api<Auth>('/admin/models/codex/login','POST',connection);setDraft(d=>d&&({...d,connections:d.connections.map(c=>c.id===connection.id?{...c,auth}:c)}))}catch(e){setError((e as Error).message)}finally{setWorking(null)}}
 const logout=async(connection:Connection)=>{setWorking(connection.id);try{await api('/admin/models/codex/'+connection.id+'/logout','POST',{});setDraft(d=>d&&({...d,connections:d.connections.map(c=>c.id===connection.id?{...c,configured:false,auth:{logged_in:false,status:'signed_out'},catalog:undefined}:c)}))}catch(e){setError((e as Error).message)}finally{setWorking(null)}}
 const save=async(candidate:Config=draft,rebuildVectors=embeddingChanged&&rebuild)=>{setBusy(true);setError('');try{const saved=await api<Config&{rebuild_queued?:boolean}>('/admin/models','PUT',{connections:candidate.connections,routes:candidate.routes,embedding_dim:candidate.embedding_dim,brief_cloud_concurrency:candidate.brief_cloud_concurrency,quality_cloud_concurrency:candidate.quality_cloud_concurrency,classify_cloud_concurrency:candidate.classify_cloud_concurrency,reading_cloud_concurrency:candidate.reading_cloud_concurrency,reading_local_concurrency:candidate.reading_local_concurrency,embedding_cloud_concurrency:candidate.embedding_cloud_concurrency,embedding_local_concurrency:candidate.embedding_local_concurrency,rebuild_vectors:rebuildVectors});result.setData(saved);toast(saved.rebuild_queued?'其他配置已保存，向量配置将在重建完成后切换':'配置已保存，新任务将使用新模型');return true}catch(e){setError((e as Error).message);return false}finally{setBusy(false)}}
 const rebuildAction=async(action:'resume'|'cancel')=>{setBusy(true);setError('');try{await api('/admin/models/embedding-rebuild/'+action,'POST',{});result.reload();toast(action==='resume'?'已安排继续重建':'已取消重建，继续使用原模型')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const pending=draft.pending_rebuild

 const openConnection=(connection?:Connection,advanced=false)=>{
  setError('');setConnectionRebuild(false);setShowKey(false);setConnectionEditor({value:connection?{...connection}:{id:'connection_'+randomId(),credential_revision:randomId(),name:'新连接',kind:'cloud',base_url:'',configured:false,api_key:''},isNew:!connection,advanced})
 }
 const editConnection=(patch:Partial<Connection>)=>setConnectionEditor(editor=>editor&&({...editor,value:{...editor.value,...patch}}))
 const applyConnection=async()=>{
  if(!connectionEditor)return
  const value=connectionEditor.value
  let candidate:Config
  if(connectionEditor.isNew)candidate={...draft,connections:[...draft.connections,value]}
  else{const old=draft.connections.find(c=>c.id===value.id)!;const patch=Object.fromEntries(Object.entries(value).filter(([key,value])=>JSON.stringify(value)!==JSON.stringify(old[key as keyof Connection]))) as Partial<Connection>;const changedCredentials='api_key' in patch||'clear_key' in patch||'kind' in patch;const changedCatalog=changedCredentials||'base_url' in patch;candidate={...draft,connections:draft.connections.map(c=>c.id===value.id?{...c,...patch,...(changedCredentials?{credential_revision:randomId()}:{}),...(changedCatalog?{catalog:undefined}:{})}:c)}}
  if(await save(candidate,requiresVectorRebuild(candidate)&&connectionRebuild)){setStatuses(s=>{const next={...s};delete next[value.id];return next});setConnectionEditor(null)}
 }
 const openFeature=(id:string,mode:'model'|'advanced')=>{
  setError('')
  const route=draft.routes[id]
  setFeatureEditor({id,mode,route:{primary:{...route.primary},fallback:route.fallback?{...route.fallback}:null},brief_cloud_concurrency:draft.brief_cloud_concurrency,quality_cloud_concurrency:draft.quality_cloud_concurrency,classify_cloud_concurrency:draft.classify_cloud_concurrency,embedding_cloud_concurrency:draft.embedding_cloud_concurrency,embedding_local_concurrency:draft.embedding_local_concurrency,embedding_dim:draft.embedding_dim,rebuild})
 }
 const editBinding=(slot:'primary'|'fallback',value:Selection|null)=>setFeatureEditor(editor=>editor&&({...editor,route:{...editor.route,[slot]:value}}))
 const applyFeature=async()=>{
  if(!featureEditor)return
  const editor=featureEditor
  const candidate:Config={...draft,routes:{...draft.routes,[editor.id]:editor.route},...(editor.id==='embedding'?{embedding_dim:editor.embedding_dim}:{}),...(editor.id==='classify'?{classify_cloud_concurrency:editor.classify_cloud_concurrency}:editor.id==='quality'?{quality_cloud_concurrency:editor.quality_cloud_concurrency}:editor.id==='brief'?{brief_cloud_concurrency:editor.brief_cloud_concurrency}:editor.id==='embedding'?{embedding_cloud_concurrency:editor.embedding_cloud_concurrency,embedding_local_concurrency:editor.embedding_local_concurrency}:{})}
  if(await save(candidate,requiresVectorRebuild(candidate)&&editor.rebuild))setFeatureEditor(null)
 }
 const visibleConnections=draft.connections.filter(c=>!c.embedding_retained&&(filter==='all'||c.kind===filter)&&(c.name+' '+c.base_url).toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name,'zh-CN'):Date.parse(b.catalog?.updated_at||'1970-01-01')-Date.parse(a.catalog?.updated_at||'1970-01-01'))
 const catalogConnection=draft.connections.find(c=>c.id===catalogId),capabilityConnection=draft.connections.find(c=>c.id===capabilityId)
 const editingFeature=featureEditor&&draft.features.find(f=>f.id===featureEditor.id),editingConnection=featureEditor&&draft.connections.find(c=>c.id===featureEditor.route.primary.connection_id)
 const editingDimensions=editingConnection?.catalog?.models.find(m=>m.id===featureEditor?.route.primary.model)?.embedding_dimensions||[]
 const featureNeedsRebuild=!!featureEditor&&featureEditor.id==='embedding'&&requiresVectorRebuild({...draft,routes:{...draft.routes,embedding:featureEditor.route},embedding_dim:featureEditor.embedding_dim})
 const connectionNeedsRebuild=!!connectionEditor&&requiresVectorRebuild({...draft,connections:connectionEditor.isNew?[...draft.connections,connectionEditor.value]:draft.connections.map(c=>c.id===connectionEditor.value.id?connectionEditor.value:c)})
 const copy=(value:string)=>void copyText(value).then(()=>toast('已复制')).catch(()=>toast('复制失败，请手动复制'))
 const groups=[
  {title:'文本理解',description:'论文理解、分类、质量评估与方向趋势',icon:FileText,ids:['classify','brief','quality','trend_report','audit']},
  {title:'研究生成',description:'智能助手、论文精读与深度解析',icon:BookOpen,ids:['chat','reading_l2','reading_l3']},
  {title:'兴趣与记忆',description:'整理研究兴趣，持续更新用户画像',icon:Brain,ids:['interest_init','reflect']},
  {title:'向量能力',description:'论文、兴趣与全文检索共用的向量空间',icon:Database,ids:['embedding']},
 ]
 const descriptions:Record<string,string>={classify:'为论文选择最相关的标准主题',brief:'生成中文标题与论文速读内容',quality:'评估论文的质量与新颖性',trend_report:'简述用户感兴趣方向的研究进展',audit:'抽样检查论文的主题分类效果',chat:'支持多轮对话、流式回复与工具调用',reading_l2:'围绕六个问题生成论文精读卡',reading_l3:'深入分析论文方法与分节内容',interest_init:'将用户描述整理为研究兴趣画像',reflect:'结合近期反馈反思并更新兴趣画像',embedding:'生成文本向量，用于相似性搜索与检索'}
 const icons:Record<string,typeof Tags>={classify:Tags,brief:Languages,quality:ShieldCheck,trend_report:TrendingUp,audit:ClipboardCheck,chat:MessageSquare,reading_l2:ScanText,reading_l3:BookMarked,interest_init:UserRound,reflect:History,embedding:Database}
 const renderVectorSpace=()=>featureEditor&&<SettingsBlock title="向量空间"><label>向量维度{editingDimensions.length?<select value={featureEditor.embedding_dim} onChange={e=>setFeatureEditor(editor=>editor&&({...editor,embedding_dim:Number(e.target.value)}))}>{!editingDimensions.includes(featureEditor.embedding_dim)&&<option value={featureEditor.embedding_dim}>{featureEditor.embedding_dim}（需改为支持的维度）</option>}{editingDimensions.map(n=><option key={n} value={n}>{n}</option>)}</select>:<input type="number" min={1} max={8192} value={featureEditor.embedding_dim} onChange={e=>setFeatureEditor(editor=>editor&&({...editor,embedding_dim:Number(e.target.value)}))}/>}</label><p className="mc-field-hint">论文、画像、检索使用同一向量空间。切换时先建立新向量，全部成功后统一切换。</p>{featureNeedsRebuild&&<label className="mc-check-row"><input type="checkbox" checked={featureEditor.rebuild} onChange={e=>setFeatureEditor(editor=>editor&&({...editor,rebuild:e.target.checked}))}/><span>安排重建<small>失败或停止时保留原模型和原向量。</small></span></label>}</SettingsBlock>
 const renderFeature=(feature:Config['features'][number],wide=false)=>{
  const Icon=icons[feature.id]||FileText
  return <FeatureCard key={feature.id} feature={{...feature,name:featureName(feature)}} icon={<Icon size={17}/>} description={descriptions[feature.id]||feature.requirement} route={draft.routes[feature.id]} connections={draft.connections} onModel={()=>openFeature(feature.id,'model')} onAdvanced={()=>openFeature(feature.id,'advanced')} wide={wide}>
   {(feature.id==='classify'||feature.id==='quality'||feature.id==='brief')&&<div className="mc-feature-metrics"><span>云端 / Codex 并发<strong>{feature.id==='classify'?draft.classify_cloud_concurrency:feature.id==='quality'?draft.quality_cloud_concurrency:draft.brief_cloud_concurrency}</strong></span></div>}
   {feature.id==='embedding'&&<><div className="mc-feature-metrics"><span>云端向量并发<strong>{draft.embedding_cloud_concurrency}</strong></span><span>本地向量并发<strong>{draft.embedding_local_concurrency}</strong></span><span>向量维度<strong>{draft.embedding_dim}</strong></span></div>{pending&&<p className="mc-field-hint">当前生效：{draft.routes.embedding.primary.model}；待切换：{pending.config.routes.embedding.primary.model} · {pending.config.embedding_dim} 维</p>}{embeddingChanged&&<div className="mc-inline-notice warning"><Info size={16}/><span>{rebuild?'已选择重建，保存后安排执行。':'向量配置已变更，请在高级设置中确认重建后保存。'}</span></div>}</>}
  </FeatureCard>
 }
 const readingResources=<section className="mc-reading-resources"><div className="mc-resource-title"><span><BookOpen size={25}/></span><div><h3>论文精读 / 深度解析并发限制</h3><p>精读请求共享队列，关闭页面后继续排队与生成。</p></div></div><div className="mc-resource-fields"><div><Cloud size={22}/><span>云端 / Codex 同时生成篇数<strong>{draft.reading_cloud_concurrency}</strong></span></div><div><Monitor size={22}/><span>本地同时生成篇数<strong>{draft.reading_local_concurrency}</strong></span></div></div><button className="mc-resource-edit" disabled={busy} onClick={()=>{setError('');setReadingEditor({cloud:draft.reading_cloud_concurrency,local:draft.reading_local_concurrency})}}><SlidersHorizontal size={15}/>调整并发</button></section>
 return <div className="model-settings mc-settings">
  <div className="tabs model-tabs" role="tablist" aria-label="模型配置">{(['connections','routing','prompts','skills'] as const).map((value,i)=><button key={value} role="tab" aria-selected={tab===value} className={tab===value?'active':''} onClick={()=>{setTab(value);if(value==='prompts'||value==='skills')setVisitedInstructions(old=>old.includes(value)?old:[...old,value])}}>{['模型连接','功能分配','Prompts','Skills'][i]}</button>)}</div>
  {visitedInstructions.includes('prompts')&&<div hidden={tab!=='prompts'}><PromptSettings/></div>}{visitedInstructions.includes('skills')&&<div hidden={tab!=='skills'}><Suspense fallback={<Loading/>}><SkillsSettings/></Suspense></div>}
  {pending&&!['prompts','skills'].includes(tab)&&<section className="mc-rebuild-notice"><div><Database size={21}/><strong>新向量重建：{({queued:'等待执行',running:'正在生成',indexing:'写入新索引',applying:'切换模型与索引',stopped:'已停止',failed:'失败，可继续'} as Record<string,string>)[pending.status]||pending.status}</strong></div><p>当前生效：{canonicalModel(draft.connections.find(c=>c.id===draft.routes.embedding.primary.connection_id),draft.routes.embedding.primary.model)}（{draft.embedding_dim} 维）；待切换：{pending.config.routes.embedding.primary.model}（{pending.config.embedding_dim} 维）。已生成 {pending.completed} / {pending.total} 篇。{pending.status==='indexing'?`索引已写入 ${pending.index_completed||0} / ${pending.index_total||0} 篇。`:pending.status==='applying'?'向量已生成，正在提交模型与索引切换。':'生成完成后还需写入索引并切换模型。'}</p>{pending.error&&<p className="error-text">{pending.error}</p>}<div className="model-actions"><button disabled={busy} onClick={result.reload}>更新进度</button><button disabled={busy||['running','queued','indexing','applying'].includes(pending.status)} onClick={()=>void rebuildAction('resume')}>继续重建</button><button disabled={busy||['running','indexing','applying'].includes(pending.status)} onClick={()=>void rebuildAction('cancel')}>取消重建</button></div></section>}
  {tab==='connections'&&<div className="mc-connections-pane">
   <div className="mc-page-heading"><div><h3>模型连接</h3><p>统一管理本地模型、云端 API 与 Codex 连接</p></div><button className="primary" disabled={busy} onClick={()=>openConnection()}><Plus size={18}/>添加连接</button></div>
   <div className="mc-toolbar"><div className="mc-filter-tabs" role="group" aria-label="筛选连接类型">{(['all','ollama','cloud','codex'] as const).map(kind=><button key={kind} aria-pressed={filter===kind} className={filter===kind?'active':''} onClick={()=>setFilter(kind)}>{kind==='all'?'全部':kindNames[kind]}<span>{draft.connections.filter(c=>!c.embedding_retained&&(kind==='all'||c.kind===kind)).length}</span></button>)}</div><div className="mc-toolbar-tools"><div className="mc-input-icon"><Search size={17}/><input aria-label="搜索连接" placeholder="搜索连接…" value={search} onChange={e=>setSearch(e.target.value)}/></div><select aria-label="连接排序" value={sort} onChange={e=>setSort(e.target.value)}><option value="updated">按更新时间</option><option value="name">按连接名称</option></select><div className="mc-view-switch"><button aria-label="卡片视图" aria-pressed={view==='grid'} onClick={()=>setView('grid')}><LayoutGrid size={18}/></button><button aria-label="列表视图" aria-pressed={view==='list'} onClick={()=>setView('list')}><List size={19}/></button></div></div></div>
   <div className={'mc-connections '+view}>{visibleConnections.map(c=><ConnectionCard key={c.id} connection={c} status={statuses[c.id]} busy={busy||working!==null&&working!==c.id} working={working===c.id} used={Object.values(draft.routes).some(r=>r.primary.connection_id===c.id||r.fallback?.connection_id===c.id)||pending?.config.routes.embedding.primary.connection_id===c.id} onEdit={()=>openConnection(c)} onRemove={()=>void save({...draft,connections:draft.connections.filter(old=>old.id!==c.id)})} onCatalog={()=>{setCatalogSearch('');setCatalogId(c.id)}} onCapabilities={()=>setCapabilityId(c.id)} onAdvanced={()=>openConnection(c,true)} onTest={()=>void action(c,false)} onRefresh={()=>void action(c,true)} onLogin={()=>void login(c)} onLogout={()=>void logout(c)} onCopy={copy}/>)}</div>
   {!visibleConnections.length&&<div className="mc-empty"><Search size={26}/><strong>没有匹配的连接</strong><p>尝试调整搜索词或连接类型。</p></div>}
   <div className="mc-page-hint"><span><Info size={20}/></span><div><strong>连接与模型能力</strong><p>测试连接后可更新模型目录。这里只显示服务支持的设置项。API Key 和 Codex 授权会加密保存，页面不会显示。</p></div></div>
  </div>}
  {tab==='routing'&&<div className="mc-routing-pane">
   {groups.map(group=>{const features=group.ids.map(id=>draft.features.find(f=>f.id===id)).filter((f):f is Config['features'][number]=>!!f),Icon=group.icon;return features.length>0&&<FeatureGroup key={group.title} title={group.title} description={group.description} icon={<Icon size={18}/>} count={features.length}>{features.map((feature,i)=>renderFeature(feature,features.length===1||i===features.length-1&&features.length%2===1))}{group.title==='研究生成'&&readingResources}</FeatureGroup>})}
   {draft.features.filter(f=>!groups.some(group=>group.ids.includes(f.id))).map(feature=>renderFeature(feature,true))}
  </div>}
  {error&&!['prompts','skills'].includes(tab)&&<ErrorBox error={error}/>}


  {readingEditor&&<SettingsDialog title="论文精读 / 深度解析并发限制" description="调整精读请求共享队列的同时生成篇数。" icon={<span className="mc-dialog-feature-icon"><BookOpen size={24}/></span>} busy={busy} error={error} onClose={()=>setReadingEditor(null)} footer={<><span className="mc-footer-hint">保存后用于新任务</span><button disabled={busy} onClick={()=>setReadingEditor(null)}>取消</button><button className="primary" disabled={busy} onClick={async()=>{if(await save({...draft,reading_cloud_concurrency:readingEditor.cloud,reading_local_concurrency:readingEditor.local}))setReadingEditor(null)}}><Check size={16}/>{busy?'正在保存…':'保存配置'}</button></>}><SettingsBlock title="同时生成篇数" description="关闭页面后仍会继续排队与生成。"><div className="mc-form-columns"><label>云端 / Codex 同时生成篇数<input type="number" min={1} max={8} value={readingEditor.cloud} onChange={e=>setReadingEditor(editor=>editor&&({...editor,cloud:Number(e.target.value)}))}/></label><label>本地同时生成篇数<input type="number" min={1} max={4} value={readingEditor.local} onChange={e=>setReadingEditor(editor=>editor&&({...editor,local:Number(e.target.value)}))}/></label></div></SettingsBlock></SettingsDialog>}
  {connectionEditor&&<SettingsDialog title={connectionEditor.isNew?'添加模型连接':connectionEditor.advanced?'Codex 高级配置':'编辑模型连接'} description="填写连接信息，保存后用于新任务。" icon={<ConnectionIcon kind={connectionEditor.value.kind}/>} busy={busy||working!==null} error={error} onClose={()=>setConnectionEditor(null)} footer={<><span className="mc-footer-hint">保存后用于新任务</span><button disabled={busy||working!==null} onClick={()=>setConnectionEditor(null)}>取消</button><button className="primary" disabled={busy||working!==null||connectionNeedsRebuild&&!connectionRebuild} onClick={()=>void applyConnection()}><Check size={16}/>{busy?'正在保存…':'保存连接'}</button></>}>
   <SettingsBlock title="连接信息" description="选择连接类型，填写名称与服务地址。">
    <div className="mc-kind-picker" role="group" aria-label="连接类型">{(['ollama','cloud','codex'] as const).map(kind=><button key={kind} aria-pressed={connectionEditor.value.kind===kind} className={connectionEditor.value.kind===kind?'active':''} onClick={()=>{if(connectionEditor.value.kind!==kind)editConnection({kind,base_url:kind==='codex'?CODEX_URL:kind==='ollama'?'http://localhost:11434':'',api_key:'',configured:false,auth:undefined,clear_key:false,catalog:undefined})}}><ConnectionIcon kind={kind}/><span>{kind==='ollama'?'本地 Ollama':kindNames[kind]}</span></button>)}</div>
    <label>连接名称<input aria-label="连接名称" value={connectionEditor.value.name} placeholder="例如：本地 Ollama / 阿里云" onChange={e=>editConnection({name:e.target.value})}/></label>
    {connectionEditor.value.kind==='codex'?<label>服务地址<select value={connectionEditor.value.base_url||CODEX_URL}><option value={connectionEditor.value.base_url||CODEX_URL}>Codex 服务（设备码流程）</option></select><small className="mc-field-hint">{connectionEditor.value.base_url||CODEX_URL}</small></label>:<label>Base URL<input aria-label="Base URL" type="url" value={connectionEditor.value.base_url} placeholder={connectionEditor.value.kind==='ollama'?'http://ollama:11434':'https://服务地址/v1'} onChange={e=>editConnection({base_url:e.target.value})}/></label>}
   </SettingsBlock>
   {connectionEditor.value.kind==='cloud'&&<SettingsBlock title="身份验证" description="填写新的 API Key，或留空保留已经保存的 Key。"><label>API Key<div className="mc-key-input"><input type={showKey?'text':'password'} aria-label="API Key" autoComplete="new-password" placeholder={connectionEditor.value.configured?'已配置，留空保留原 Key':'填写 API Key'} value={connectionEditor.value.api_key||''} onChange={e=>editConnection({api_key:e.target.value,clear_key:false})}/><button type="button" className="icon-button" aria-label={showKey?'隐藏新输入的 API Key':'显示新输入的 API Key'} disabled={!connectionEditor.value.api_key} onClick={()=>setShowKey(!showKey)}>{showKey?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label><label className="mc-check-row"><input type="checkbox" checked={!!connectionEditor.value.clear_key} onChange={e=>editConnection({clear_key:e.target.checked,api_key:''})}/><span>清除已保存的 Key<small>保存配置后生效。</small></span></label></SettingsBlock>}
   {connectionEditor.value.kind==='codex'&&<><SettingsBlock title="兼容版本" description="沿用现有版本检测和验证方式。"><div className="mc-form-columns"><label>兼容版本更新<select aria-label={connectionEditor.value.name+'兼容版本更新'} value={connectionEditor.value.codex_auto_update===false?'manual':'auto'} onChange={e=>editConnection({codex_auto_update:e.target.value==='auto',codex_client_version:connectionEditor.value.codex_client_version||connectionEditor.value.catalog?.compatibility?.active_version||'0.160.0'})}><option value="auto">自动检测官方稳定版本</option><option value="manual">手动指定版本</option></select></label>{connectionEditor.value.codex_auto_update===false&&<label>指定兼容版本<input aria-label={connectionEditor.value.name+'指定兼容版本'} value={connectionEditor.value.codex_client_version||'0.160.0'} maxLength={20} placeholder="如 0.160.0" onChange={e=>editConnection({codex_client_version:e.target.value})}/></label>}</div><div className="mc-version-summary"><span>已验证版本<strong>{connectionEditor.value.catalog?.compatibility?.active_version||'尚未验证'}</strong></span><span>官方稳定版<strong>{connectionEditor.value.catalog?.compatibility?.latest_version||'尚未检查'}</strong></span></div><p className="mc-field-hint">更新可用模型时检查版本；版本变化时用少量 token 验证实际流式回复，通过后采用。失败保留原版本和目录。</p>{connectionEditor.value.catalog?.compatibility?.validated_at&&<p className="mc-field-hint">最近验证：{new Date(connectionEditor.value.catalog.compatibility.validated_at).toLocaleString()} · {connectionEditor.value.catalog.compatibility.validation_model}</p>}</SettingsBlock><SettingsBlock title="OAuth 高级配置"><label>OAuth Client ID<input value={connectionEditor.value.oauth_client_id||'app_EMoamEEZ73f0CkXaXp7hrann'} onChange={e=>editConnection({oauth_client_id:e.target.value})}/></label><p className="mc-field-hint">设备码登录自己的 ChatGPT 账户，无需 Codex CLI；可用模型与额度由账户权限决定。</p></SettingsBlock></>}
   {connectionNeedsRebuild&&<SettingsBlock title="向量空间变更"><p className="mc-field-hint">此连接用于向量生成。修改服务地址或类型需要先重建新向量。</p><label className="mc-check-row"><input type="checkbox" checked={connectionRebuild} onChange={e=>setConnectionRebuild(e.target.checked)}/><span>安排重建<small>失败或停止时保留原模型和原向量。</small></span></label></SettingsBlock>}
  </SettingsDialog>}
  {catalogConnection&&<SettingsDialog title={catalogConnection.name+' · 可用模型'} description={catalogConnection.catalog?.updated_at?'目录更新于 '+new Date(catalogConnection.catalog.updated_at).toLocaleString():'尚未更新模型目录'} icon={<ConnectionIcon kind={catalogConnection.kind}/>} onClose={()=>setCatalogId(null)} footer={<><span className="mc-footer-hint">{catalogConnection.catalog?.models.length||0} 个可用模型</span><button disabled={busy||working!==null||!catalogConnection.base_url} onClick={()=>void action(catalogConnection,true)}><RefreshCw size={15} className={working===catalogConnection.id?'animate-spin':undefined}/>更新可用模型</button><button onClick={()=>setCatalogId(null)}>关闭</button></>}><div className="mc-input-icon"><Search size={17}/><input aria-label="搜索模型目录" placeholder="搜索模型名称…" value={catalogSearch} onChange={e=>setCatalogSearch(e.target.value)}/></div><div className="mc-catalog-list">{catalogConnection.catalog?.models.filter(m=>(m.id+' '+m.name).toLowerCase().includes(catalogSearch.toLowerCase())).map(m=><article key={m.id}><span><Box size={19}/></span><div><strong>{m.id}</strong><p>{m.name&&m.name!==m.id?m.name+' · ':''}{sourceNames[m.capability_source||'unknown']}</p><div>{m.thinking_modes.filter(mode=>mode!=='auto').map(mode=><small key={mode}>{thinkingNames[mode]}</small>)}{m.reasoning_efforts.length>0&&<small>推理：{m.reasoning_efforts.map(e=>effortNames[e]||e).join(' / ')}</small>}{!!m.embedding_dimensions?.length&&<small>维度：{m.embedding_dimensions.join(' / ')}</small>}</div></div><small className="mc-requirement">{m.type==='embedding'?'向量模型':m.type==='chat'?'文本生成':'类型待确认'}</small></article>)}</div>{!catalogConnection.catalog?.models.length&&<div className="mc-empty"><Box size={28}/><strong>尚无可用模型目录</strong><p>更新模型目录后即可在这里查看。</p></div>}{statuses[catalogConnection.id]&&<p className={statuses[catalogConnection.id].ok?'mc-success-text':'error-text'}>{statuses[catalogConnection.id].message}</p>}</SettingsDialog>}
  {capabilityConnection&&<CapabilityEditor connection={capabilityConnection} onClose={()=>setCapabilityId(null)} onCatalog={catalog=>setDraft(d=>d&&({...d,connections:d.connections.map(c=>c.id===capabilityConnection.id?{...c,catalog}:c)}))}/>}
  {featureEditor&&editingFeature&&<SettingsDialog title={featureName(editingFeature)+' · 功能配置'} description="选择模型并调整参数，保存后用于新任务。" icon={<span className="mc-dialog-feature-icon"><SlidersHorizontal size={24}/></span>} busy={busy||working!==null} error={error} onClose={()=>setFeatureEditor(null)} footer={<><span className="mc-footer-hint">保存后用于新任务</span><button disabled={busy} onClick={()=>setFeatureEditor(null)}>取消</button><button className="primary" disabled={busy||working!==null||featureNeedsRebuild&&!featureEditor.rebuild||!!featureEditor.route.primary.connection_id!==!!featureEditor.route.primary.model.trim()||!!featureEditor.route.fallback&&(!featureEditor.route.fallback.connection_id||!featureEditor.route.fallback.model.trim())} onClick={()=>void applyFeature()}><Check size={16}/>{busy?'正在保存…':'保存配置'}</button></>}>
   <div className="mc-feature-tabs" role="tablist" aria-label="功能配置">{(['model','advanced'] as const).map((mode,i)=><button key={mode} id={'feature-editor-'+mode} type="button" role="tab" data-mode={mode} aria-selected={featureEditor.mode===mode} aria-controls="feature-editor-panel" tabIndex={featureEditor.mode===mode?0:-1} disabled={busy||working!==null} onClick={()=>setFeatureEditor(editor=>editor&&({...editor,mode}))} onKeyDown={event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const next=event.key==='Home'?'model':event.key==='End'?'advanced':mode==='model'?'advanced':'model';setFeatureEditor(editor=>editor&&({...editor,mode:next}));event.currentTarget.parentElement?.querySelector<HTMLButtonElement>('[data-mode="'+next+'"]')?.focus()}}>{['更改模型','高级设置'][i]}</button>)}</div>
   <div className="mc-current-selection"><span>当前配置</span><strong>{editingConnection?kindNames[editingConnection.kind]+' · '+editingConnection.name:'未选择连接'} / {featureEditor.route.primary.model||'未选择模型'}</strong></div>
   <div id="feature-editor-panel" role="tabpanel" aria-labelledby={'feature-editor-'+featureEditor.mode}>{featureEditor.mode==='model'?<><SettingsBlock title="选择模型" description={'功能要求：'+editingFeature.requirement}><ModelChoice mode="model" label={featureName(editingFeature)} feature={editingFeature.id} binding={featureEditor.route.primary} connections={draft.connections} onChange={value=>editBinding('primary',value)}/></SettingsBlock>{editingFeature.id==='embedding'&&renderVectorSpace()}</>:<>
    {editingFeature.id!=='embedding'&&<SettingsBlock title="模型参数" description="根据当前模型的能力开放思考模式和推理强度。"><ModelChoice mode="advanced" label={featureName(editingFeature)} feature={editingFeature.id} binding={featureEditor.route.primary} connections={draft.connections} onChange={value=>editBinding('primary',value)}/></SettingsBlock>}
    {editingFeature.id==='classify'&&<SettingsBlock title="运行并发"><label>云端 / Codex 并发数<input type="number" min={1} max={16} value={featureEditor.classify_cloud_concurrency} onChange={e=>setFeatureEditor(editor=>editor&&({...editor,classify_cloud_concurrency:Number(e.target.value)}))}/></label><p className="mc-field-hint">云端 API 和 Codex 可设置 1–16 路，本地分类固定单路。保存后新启动的分类与重做任务使用此设置。</p></SettingsBlock>}
    {(editingFeature.id==='quality'||editingFeature.id==='brief')&&<SettingsBlock title="运行并发"><label>云端 / Codex 并发数<input type="number" min={1} max={8} value={editingFeature.id==='quality'?featureEditor.quality_cloud_concurrency:featureEditor.brief_cloud_concurrency} onChange={e=>setFeatureEditor(editor=>editor&&({...editor,[editingFeature.id==='quality'?'quality_cloud_concurrency':'brief_cloud_concurrency']:Number(e.target.value)}))}/></label></SettingsBlock>}
    {editingFeature.id==='embedding'&&<><SettingsBlock title="向量生成并发"><div className="mc-form-columns"><label>云端向量并发路数<input type="number" min={1} max={16} value={featureEditor.embedding_cloud_concurrency} onChange={e=>setFeatureEditor(editor=>editor&&({...editor,embedding_cloud_concurrency:Number(e.target.value)}))}/></label><label>本地向量并发路数<input type="number" min={1} max={4} value={featureEditor.embedding_local_concurrency} onChange={e=>setFeatureEditor(editor=>editor&&({...editor,embedding_local_concurrency:Number(e.target.value)}))}/></label></div><p className="mc-field-hint">后台与前台共享总额度。总路数大于 1 时，后台最多使用总路数减 1，为检索保留一条路数；按模型批量上限自动拆分。</p></SettingsBlock>{renderVectorSpace()}</>}
    {editingFeature.id!=='embedding'&&<SettingsBlock title="备用模型" description="主模型调用失败时，沿用现有备用模型处理方式。"><label className="mc-check-row"><input type="checkbox" checked={!!featureEditor.route.fallback} onChange={e=>editBinding('fallback',e.target.checked?{connection_id:'',model:''}:null)}/><span>失败时使用备用模型</span></label>{featureEditor.route.fallback&&<div className="mc-fallback-editor"><ModelChoice label={featureName(editingFeature)+'备用'} feature={editingFeature.id} binding={featureEditor.route.fallback} connections={draft.connections} onChange={value=>editBinding('fallback',value)}/></div>}</SettingsBlock>}
   </>}</div>
  </SettingsDialog>}
 </div>
}
