import type {RefObject} from 'react'
import {ArrowUpRight,Check,Mail,MoreHorizontal,Trash2} from 'lucide-react'
import {MathText} from './MathText'
import {formatTime} from './Common'

export interface Notice {id:number;type:string;title:string;body:string|null;paper_id:number|null;read:number;created_at:string}
export const noticeTypes:Record<string,string>={watch_hit:'监视命中',baseline_beaten:'Baseline 相关比较',collision:'在研方向预警',trend_report:'历史趋势通知'}

export function NotificationTable({items,selected,busy,selectAll,allSelected,onSelectPage,onSelect,onOpen,onRead,onDelete}:{items:Notice[];selected:number[];busy:boolean;selectAll:RefObject<HTMLInputElement>;allSelected:boolean;onSelectPage:(checked:boolean)=>void;onSelect:(id:number,checked:boolean)=>void;onOpen:(notice:Notice)=>void;onRead:(notice:Notice)=>void;onDelete:(notice:Notice)=>void}){
 return <table className="notice-table"><caption className="sr-only">通知列表</caption><colgroup><col className="notice-check-col"/><col/><col className="notice-kind-col"/><col className="notice-state-col"/><col className="notice-time-col"/><col className="notice-actions-col"/></colgroup><thead><tr><th scope="col"><input ref={selectAll} type="checkbox" aria-label="全选当前页通知" checked={allSelected} disabled={busy} onChange={e=>onSelectPage(e.target.checked)}/></th><th scope="col">通知内容</th><th className="notice-kind-col" scope="col">类型</th><th className="notice-state-col" scope="col">状态</th><th className="notice-time-col" scope="col">时间</th><th scope="col" className="notice-actions-col">操作</th></tr></thead><tbody>{items.map(n=><tr key={n.id} className={(n.read?'':'notice-unread ')+(selected.includes(n.id)?'notice-selected':'')}>
  <td><input type="checkbox" aria-label={'选择通知：'+n.title} checked={selected.includes(n.id)} disabled={busy} onChange={e=>onSelect(n.id,e.target.checked)}/></td>
  <td className="notice-content-cell"><div className="notice-content"><span className={'notice-read-dot '+(n.read?'is-read':'')} aria-label={n.read?'已读':'未读'}/><div><button type="button" className="notice-title" disabled={busy} onClick={()=>onOpen(n)}><MathText inline>{n.title}</MathText></button>{n.body&&<p className="notice-excerpt"><MathText inline>{n.body}</MathText></p>}<div className="notice-mobile-meta"><span className={'notice-kind '+n.type}>{noticeTypes[n.type]||n.type}</span><time dateTime={n.created_at}>{formatTime(n.created_at)}</time></div></div></div></td>
  <td className="notice-kind-col"><span className={'notice-kind '+n.type}>{noticeTypes[n.type]||n.type}</span></td><td className="notice-state-col"><span className={'notice-state '+(n.read?'is-read':'')}>{n.read?'已读':'未读'}</span></td><td className="notice-time-col"><time dateTime={n.created_at}>{formatTime(n.created_at)}</time></td>
  <td className="notice-actions-col"><div className="notice-row-actions"><button type="button" className="notice-view" disabled={busy} aria-label={'查看通知：'+n.title} onClick={()=>onOpen(n)}>查看<ArrowUpRight size={13}/></button><details className="notice-more" onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))e.currentTarget.open=false}}><summary aria-label={'管理通知：'+n.title} aria-disabled={busy} tabIndex={busy?-1:0} onClick={e=>{if(busy)e.preventDefault()}}><MoreHorizontal size={18}/></summary><div className="notice-more-menu"><button type="button" disabled={busy} onClick={e=>{e.currentTarget.closest('details')!.open=false;onOpen(n)}}><ArrowUpRight size={14}/>查看通知</button><button type="button" disabled={busy} onClick={e=>{e.currentTarget.closest('details')!.open=false;onRead(n)}}>{n.read?<Mail size={14}/>:<Check size={14}/>}标为{n.read?'未读':'已读'}</button><button type="button" className="notice-danger" disabled={busy} onClick={e=>{e.currentTarget.closest('details')!.open=false;onDelete(n)}}><Trash2 size={14}/>删除通知</button></div></details></div></td>
 </tr>)}</tbody></table>
}
