import {ChevronDown,ChevronRight,Pencil,Trash2} from 'lucide-react'
import {groupSources} from '../disciplines'
import type {Source} from './SourceManager'
import {useTreeExpansion} from '../hooks/useTreeExpansion'
import {TreeExpansionControls} from './TreeExpansionControls'

export function SourceTable({sources,pageItems,selected,busy,deletionPending,search,onSelectPage,onSelect,onEdit,onDelete,onConfig}:{sources:Source[];pageItems:Source[];selected:string[];busy:boolean;deletionPending:boolean;search:string;onSelectPage:(checked:boolean)=>void;onSelect:(key:string,checked:boolean)=>void;onEdit:(source:Source)=>void;onDelete:(source:Source)=>void;onConfig:(source:Source,key:'fetch_enabled'|'guest_default',checked:boolean)=>void}){
 const tree=useTreeExpansion(search.trim().toLowerCase())
 const totals=groupSources(sources),groups=groupSources(pageItems)
 return <div className="panel table-wrap source-list-panel"><div className="source-tree-toolbar"><TreeExpansionControls variant="buttons" onExpand={()=>tree.setAll(totals.map(g=>g.key),true)} onCollapse={()=>tree.setAll(totals.map(g=>g.key),false)}/></div><table className="source-manager-table"><thead><tr><th><input type="checkbox" aria-label="全选当前页分类" checked={pageItems.some(s=>!s.deletion_id)&&pageItems.filter(s=>!s.deletion_id).every(s=>selected.includes(s.key))} disabled={busy||!pageItems.some(s=>!s.deletion_id)} onChange={e=>onSelectPage(e.target.checked)}/></th><th>分类</th><th>论文数</th><th>自动抓取</th><th>游客默认</th><th>排序</th><th>操作</th></tr></thead>{groups.map(group=>{
  const open=tree.isOpen(group.key),selectedCount=totals.find(g=>g.key===group.key)?.sources.filter(s=>selected.includes(s.key)).length||0
  return <tbody key={group.key}><tr className="source-discipline-row"><th colSpan={7} scope="rowgroup"><button type="button" aria-label={(open?'收起':'展开')+group.label+'来源'} aria-expanded={open} onClick={()=>tree.toggle(group.key)}>{open?<ChevronDown size={16}/>:<ChevronRight size={16}/>}<span>{group.label}</span>{selectedCount>0&&<span className="tree-selection-summary">已选 {selectedCount}</span>}<small>{totals.find(g=>g.key===group.key)?.sources.length} 项</small></button></th></tr>{open&&group.sources.map(s=><tr key={s.key} className={selected.includes(s.key)?"row-selected":""}><td className="source-selection"><input type="checkbox" aria-label={'选择分类：'+s.code} checked={selected.includes(s.key)} disabled={busy||!!s.deletion_id} onChange={e=>onSelect(s.key,e.target.checked)}/></td><td><strong className="management-source-code">{s.code}</strong><small><span className={"source-kind "+s.kind}>{s.kind==='arxiv'?'arXiv':'会议'}</span>{s.label}</small>{!!s.deletion_id&&<span className="source-deleting-label">后台删除中</span>}</td><td data-label="论文数">{s.paper_count}</td>{(['fetch_enabled','guest_default'] as const).map(key=><td key={key} data-label={key==='fetch_enabled'?'自动抓取':'游客默认'}><input type="checkbox" aria-label={s.code+' '+(key==='fetch_enabled'?'自动抓取':'游客默认')} checked={!!s[key]} disabled={busy||!!s.deletion_id} onChange={e=>onConfig(s,key,e.target.checked)}/></td>)}<td data-label="排序">{s.sort_order}</td><td className="source-table-actions"><button disabled={busy||!!s.deletion_id} onClick={()=>onEdit(s)}><Pencil size={14}/>编辑</button><button className="danger" disabled={busy||deletionPending||!!s.deletion_id} onClick={()=>onDelete(s)}><Trash2 size={14}/>删除</button></td></tr>)}</tbody>
 })}</table>{!sources.length&&<p className="tree-empty">没有匹配的分类。</p>}</div>
}
