import {useState,useEffect,type ReactNode} from 'react'
import {Link} from 'react-router-dom'
import {BookOpen,Users,MousePointerClick,Coins,Database,ChartNoAxesCombined,CheckSquare,Play,ChevronRight,Activity,FolderTree,BarChart3,type LucideIcon} from 'lucide-react'
import {ResponsiveContainer,BarChart,Bar,LabelList,LineChart,Line,AreaChart,Area,XAxis,YAxis,CartesianGrid,Tooltip,Legend} from 'recharts'
import {useLoad} from '../hooks/useLoad'
import {Loading,ErrorBox,formatTime} from '../components/Common'
import {IconTile} from '../components/PageContentUI'
import {taskNames as names} from '../components/taskNames'
import {DailyReadingMetrics} from '../components/DailyReadingMetrics'
import '../admin-overview.css'

type Usage={input_tokens:number;output_tokens:number;calls:number;unknown_usage?:number;model?:string;label?:string;connection_id?:string|null}
type Overview={subscription_usage?:Usage[];days:number;updated_at:string;totals:{papers:number;users:number;active_users_7d:number;today_papers:number;today_shown:number;today_actions:number;today_input_tokens:number;today_output_tokens:number;today_unknown_usage:number};pending:{classification:number;embedding:number;brief:number;topics:number};timeline:{date:string;papers:number;shown:number;active_users:number;input_tokens:number;output_tokens:number}[];categories:{code:string;kind:string;count:number}[];by_model:Usage[];by_feature:Usage[];by_connection:Usage[];jobs:{name:string;running:number;error:string|null;last_success:string|null;status:string}[]}
const number=(value:number)=>value.toLocaleString('zh-CN')
const axis={fontSize:11,fill:'var(--secondary)'}
const jobLabels:Record<string,string>={running:'运行中',disabled:'已禁用',stopped:'已停止',error:'需检查',ready:'成功',pending:'尚未运行'}
function ChartCard({title,description,icon,tone='blue',legend,children}:{title:string;description:string;icon:LucideIcon;tone?:'blue'|'purple'|'green';legend?:ReactNode;children:ReactNode}){
 return <section className="panel overview-chart"><header className="overview-section-heading"><IconTile icon={icon} tone={tone}/><div><h2>{title}</h2><p>{description}</p></div>{legend}</header><div className="overview-chart-canvas">{children}</div></section>
}
export function AdminOverview({base}:{base:string}){
 const [days,setDays]=useState(7),[group,setGroup]=useState<'model'|'feature'|'connection'>('model'),[allJobs,setAllJobs]=useState(false)
 const result=useLoad<Overview>('/admin/overview?days='+days)
 useEffect(()=>{const timer=setInterval(()=>{if(document.visibilityState==='visible')result.reload()},60000);return()=>clearInterval(timer)},[result.reload])
 if(result.error)return <ErrorBox error={result.error} reload={result.reload}/>
 if(!result.data)return <Loading/>
 const data=result.data,t=data.totals,usage=group==='model'?data.by_model:group==='feature'?data.by_feature:data.by_connection
 const paperAxisWidth=Math.max(50,(number(Math.max(0,...data.timeline.map(day=>day.papers))).length+1)*7+16)
 const cards=[{title:'论文总数',value:t.papers,hint:'今日新增 '+number(t.today_papers)+' 篇',Icon:BookOpen,tone:'blue'},{title:'注册用户',value:t.users,hint:'近 7 天活跃 '+number(t.active_users_7d)+' 人',Icon:Users,tone:'purple'},{title:'今日已刷',value:t.today_shown,hint:'今日互动 '+number(t.today_actions)+' 次',Icon:MousePointerClick,tone:'green'},{title:'今日云端 token',value:t.today_input_tokens+t.today_output_tokens,hint:'输入 '+number(t.today_input_tokens)+' · 输出 '+number(t.today_output_tokens),Icon:Coins,tone:'blue'}] as const
 const jobs=[...data.jobs].sort((a,b)=>Number(b.status==='running'||b.status==='error')-Number(a.status==='running'||a.status==='error')||(b.last_success||'').localeCompare(a.last_success||''))
 const shownJobs=allJobs?jobs:jobs.slice(0,4)
 return <div className="admin-overview">
  <header className="overview-toolbar"><div><h1 className="admin-page-title">概览</h1><p>本站数据与模型用量</p></div><div className="overview-period-tabs" aria-label="概览统计时间">{[7,30].map(n=><button key={n} className={days===n?'active':''} aria-pressed={days===n} onClick={()=>setDays(n)}>近 {n} 天</button>)}</div></header>
  <div className="overview-cards">{cards.map(({title,value,hint,Icon,tone})=><section className="panel overview-card" key={title}><IconTile icon={Icon} tone={tone}/><div className="overview-card-value"><h2>{title}</h2><strong>{number(value)}</strong><p>{hint}</p></div></section>)}</div>
  {t.today_unknown_usage>0&&<p className="overview-usage-note">今日有 {t.today_unknown_usage} 次云端响应未返回 token 用量，未计入 token 总数。</p>}
  <div className="overview-charts overview-primary-charts">
   <ChartCard title="论文入库" description={'近 '+days+' 天每日新增论文'} icon={BookOpen}><ResponsiveContainer width="100%" height="100%"><BarChart data={data.timeline} margin={{top:20,right:8,left:0,bottom:0}}><defs><linearGradient id="overview-paper-bars" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#3568ff"/><stop offset="100%" stopColor="#6a91ff"/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--border)"/><XAxis dataKey="date" tickFormatter={v=>v.slice(5)} tick={axis} axisLine={false} tickLine={false} minTickGap={16}/><YAxis allowDecimals={false} tick={axis} width={paperAxisWidth} tickMargin={8} tickFormatter={number} axisLine={false} tickLine={false}/><Tooltip cursor={{fill:'var(--overview-soft)'}}/><Bar dataKey="papers" name="新增论文" fill="url(#overview-paper-bars)" radius={[4,4,0,0]} maxBarSize={34} isAnimationActive={false}>{days===7&&<LabelList dataKey="papers" position="top" fill="var(--overview-blue)" fontSize={11}/>}</Bar></BarChart></ResponsiveContainer></ChartCard>
   <ChartCard title="云端 token 消耗" description={'近 '+days+' 天模型调用的输入与输出'} icon={Database} tone="purple" legend={<div className="overview-chart-legend"><span><i className="blue"/>输入 token</span><span><i className="purple"/>输出 token</span></div>}><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.timeline} margin={{top:20,right:9,left:-5,bottom:0}}><defs><linearGradient id="overview-token-input" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#3568ff" stopOpacity={.22}/><stop offset="100%" stopColor="#3568ff" stopOpacity={.02}/></linearGradient><linearGradient id="overview-token-output" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#8b5cf6" stopOpacity={.23}/><stop offset="100%" stopColor="#8b5cf6" stopOpacity={.03}/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--border)"/><XAxis dataKey="date" tickFormatter={v=>v.slice(5)} tick={axis} axisLine={false} tickLine={false} minTickGap={16}/><YAxis tick={axis} width={48} axisLine={false} tickLine={false} tickFormatter={v=>v>=1000?(v/1000).toFixed(0)+'k':v}/><Tooltip/><Area type="monotone" dataKey="input_tokens" name="输入 token" stroke="#3568ff" strokeWidth={2} fill="url(#overview-token-input)" dot={days===7?{r:3,strokeWidth:1,stroke:'var(--card)'}:false} isAnimationActive={false}/><Area type="monotone" dataKey="output_tokens" name="输出 token" stroke="#8b5cf6" strokeWidth={2} fill="url(#overview-token-output)" dot={days===7?{r:3,strokeWidth:1,stroke:'var(--card)'}:false} isAnimationActive={false}/></AreaChart></ResponsiveContainer></ChartCard>
  </div>
  <DailyReadingMetrics/>
  <div className="overview-bottom">
   <section className="panel overview-pending"><header className="overview-section-heading"><IconTile icon={CheckSquare}/><div><h2>待处理事项</h2><p>需要处理的论文与主题</p></div></header><div className="overview-pending-grid">{([['classification','待分类论文'],['embedding','待生成向量'],['brief','待生成解读'],['topics','待批准主题']] as const).map(([key,label])=><Link to={base+(key==='topics'?'/topics':'/pipeline')} key={key}><span>{label}</span><strong>{number(data.pending[key])}</strong><ChevronRight size={15}/></Link>)}</div></section>
   <section className="panel overview-jobs"><header className="overview-section-heading"><IconTile icon={Play} tone="green"/><div><h2>任务状态</h2><p>优先显示运行中、异常与最近完成的任务</p></div><Link to={base+'/pipeline'}>查看全部<ChevronRight size={14}/></Link></header><div className="overview-job-list">{shownJobs.map(job=><div key={job.name}><span title={names[job.name]||job.name}>{names[job.name]||job.name}</span><small>{job.last_success?formatTime(job.last_success):'尚无成功记录'}</small><span className={'overview-job-state '+job.status}><i/>{jobLabels[job.status]||job.status}</span></div>)}</div>{!data.jobs.length&&<p className="overview-empty">尚无任务运行记录。</p>}{jobs.length>4&&<button className="overview-jobs-expand" aria-expanded={allJobs} onClick={()=>setAllJobs(value=>!value)}>{allJobs?'收起任务状态':'展开全部 '+jobs.length+' 项任务状态'}</button>}</section>
  </div>
  <div className="overview-charts overview-secondary-charts">
   <ChartCard title="阅读活动" description="停留达到阅读阈值的论文与活跃用户" icon={Activity} tone="green"><ResponsiveContainer width="100%" height="100%"><LineChart data={data.timeline}><CartesianGrid vertical={false} stroke="var(--border)"/><XAxis dataKey="date" tickFormatter={v=>v.slice(5)} tick={axis} axisLine={false} tickLine={false}/><YAxis allowDecimals={false} tick={axis} width={44} axisLine={false} tickLine={false}/><Tooltip/><Legend/><Line type="monotone" dataKey="shown" name="已刷论文" stroke="#3568ff" strokeWidth={2} dot={false} isAnimationActive={false}/><Line type="monotone" dataKey="active_users" name="活跃用户" stroke="#10b981" strokeWidth={2} dot={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></ChartCard>
   <ChartCard title="分类与会议分布" description="一篇跨类论文可以计入多个分类" icon={FolderTree} tone="purple"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.categories} layout="vertical" margin={{left:0,right:15}}><CartesianGrid horizontal={false} stroke="var(--border)"/><XAxis type="number" tick={axis} allowDecimals={false} axisLine={false} tickLine={false}/><YAxis dataKey="code" type="category" width={72} tick={axis} axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="count" name="论文数" fill="#18ae88" radius={[0,4,4,0]} maxBarSize={20} isAnimationActive={false}/></BarChart></ResponsiveContainer></ChartCard>
  </div>
  <section className="panel overview-usage"><header className="overview-section-heading"><IconTile icon={BarChart3}/><div><h2>云端用量明细</h2><p>近 {days} 天 · 历史记录中未标注的功能与连接单独归组</p></div><select aria-label="云端用量分组" value={group} onChange={e=>setGroup(e.target.value as typeof group)}><option value="model">按模型</option><option value="feature">按功能</option><option value="connection">按连接</option></select></header><div className="table-wrap"><table><thead><tr><th>{group==='model'?'模型':group==='feature'?'功能':'连接'}</th><th>调用次数</th><th>输入 token</th><th>输出 token</th><th>总 token</th></tr></thead><tbody>{usage.map((row,i)=><tr key={i}><td>{row.model||row.label||row.connection_id||'历史 / 未标注连接'}{!!row.unknown_usage&&<small>{row.unknown_usage} 次未返回用量</small>}</td><td>{number(row.calls)}</td><td>{number(row.input_tokens||0)}</td><td>{number(row.output_tokens||0)}</td><td>{number((row.input_tokens||0)+(row.output_tokens||0))}</td></tr>)}</tbody></table>{!usage.length&&<p className="overview-empty">这一时期尚无云端调用记录。</p>}</div></section>
  {!!data.subscription_usage?.length&&<section className="panel overview-usage"><header className="overview-section-heading"><IconTile icon={Coins} tone="purple"/><div><h2>Codex 用量（独立统计）</h2><p>近 {days} 天 · 响应返回的 token，不计入云端 API 用量，不表示账户剩余额度或账单费用。</p></div></header><div className="table-wrap"><table><thead><tr><th>模型</th><th>调用次数</th><th>输入 token</th><th>输出 token</th></tr></thead><tbody>{data.subscription_usage.map(row=><tr key={row.model}><td>{row.model}{!!row.unknown_usage&&<small>{row.unknown_usage} 次未返回用量</small>}</td><td>{number(row.calls)}</td><td>{number(row.input_tokens||0)}</td><td>{number(row.output_tokens||0)}</td></tr>)}</tbody></table></div></section>}
  <p className="overview-updated">更新于 {formatTime(data.updated_at)}</p>
 </div>
}
